export const BEGINNER_LESSONS = [
  {
    id: "home-row-anchor",
    title: "Home Row Anchor Keys",
    description: "Start with the center anchor keys and build clean rhythm with your index fingers.",
    focusKeys: ["f", "j"],
    text: "f j f j ff jj fj jf fff jjj fjfj jfjf",
  },
  {
    id: "index-control",
    title: "Index Finger Control",
    description: "Strengthen your index fingers with short, repeating patterns that stay close to home row.",
    focusKeys: ["f", "g", "h", "j"],
    text: "fg hj fg hj fghj hjgf fghh jjhg ghfj",
  },
  {
    id: "left-home-basics",
    title: "Left Home Basics",
    description: "Bring the left hand home row into focus and keep your fingers returning to their anchor spots.",
    focusKeys: ["a", "s", "d", "f"],
    text: "asdf asdf sad fad dad sass adds fast",
  },
  {
    id: "right-home-basics",
    title: "Right Home Basics",
    description: "Train the right hand home row with light movement and steady timing.",
    focusKeys: ["j", "k", "l", ";"],
    text: "jkl; jkl; lad all ask fall flask alas",
  },
  {
    id: "home-row-bridge",
    title: "Home Row Bridge",
    description: "Connect both hands across the home row without lifting your wrists.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";"],
    text: "asdf jkl; asdf jkl; sad fad ask flask fall lad alas",
  },
  {
    id: "home-row-words",
    title: "Home Row Words",
    description: "Turn the home row into real words and keep the movement calm and clean.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";"],
    text: "all add fall ask flask salad lad dads flask sad",
  },
  {
    id: "top-row-left-intro",
    title: "Top Row Left Reach",
    description: "Reach up with the left hand and come back home after every stroke.",
    focusKeys: ["q", "w", "e", "r"],
    text: "qw er qw er were weir wire queer rear",
  },
  {
    id: "top-row-right-intro",
    title: "Top Row Right Reach",
    description: "Practice the right side of the top row with smooth upward movement.",
    focusKeys: ["u", "i", "o", "p"],
    text: "ui op ui op pour your pure piper rope",
  },
  {
    id: "top-row-flow",
    title: "Top Row Flow",
    description: "Blend the full top row while keeping your fingers relaxed on the return.",
    focusKeys: ["q", "w", "e", "r", "u", "i", "o", "p"],
    text: "power wire proof quiet write rope pure worry",
  },
  {
    id: "top-home-mix",
    title: "Top and Home Mix",
    description: "Move between top row and home row with light, controlled transitions.",
    focusKeys: ["q", "w", "e", "r", "a", "s", "d", "f", "j", "k", "l", ";", "u", "i", "o", "p"],
    text: "we are all ready for safe pure words and quiet flow",
  },
  {
    id: "bottom-row-left-intro",
    title: "Bottom Row Left Reach",
    description: "Drop to the lower left row and return to home without collapsing your hand shape.",
    focusKeys: ["z", "x", "c", "v"],
    text: "zx cv zx cv civic cave exact waxy zesty",
  },
  {
    id: "bottom-row-right-intro",
    title: "Bottom Row Right Reach",
    description: "Use the right hand lower row with gentle motion and accurate returns.",
    focusKeys: ["n", "m", ",", "."],
    text: "nm ,. nm ,. moon noon menu minor comma",
  },
  {
    id: "bottom-row-center",
    title: "Bottom Row Center Control",
    description: "Bring the center lower keys into short, easy patterns.",
    focusKeys: ["c", "v", "b", "n", "m"],
    text: "calm cabin vivid mimic comic vivid calm move",
  },
  {
    id: "bottom-row-flow",
    title: "Bottom Row Flow",
    description: "Mix the lower row into short words while staying accurate and relaxed.",
    focusKeys: ["z", "x", "c", "v", "b", "n", "m", ",", "."],
    text: "zinc cabin mix main vivid max comic value brave",
  },
  {
    id: "three-row-left",
    title: "Three Row Left Hand",
    description: "Use the full left hand across top, home, and bottom rows in one lesson.",
    focusKeys: ["q", "w", "e", "r", "a", "s", "d", "f", "z", "x", "c", "v"],
    text: "we crave safer exact waves and we save every area",
  },
  {
    id: "three-row-right",
    title: "Three Row Right Hand",
    description: "Let the right hand cover all three rows with balanced movement.",
    focusKeys: ["u", "i", "o", "p", "j", "k", "l", ";", "n", "m", ",", "."],
    text: "our junior pilot will join more people in common union",
  },
  {
    id: "row-balance",
    title: "Row Balance",
    description: "Build confidence by moving across all letter rows in short phrases.",
    focusKeys: ["q", "w", "e", "r", "u", "i", "o", "p", "a", "s", "d", "f", "j", "k", "l", ";", "z", "x", "c", "v", "b", "n", "m", ",", "."],
    text: "we move across our keyboard with calm focus and clean rhythm",
  },
  {
    id: "slash-and-punctuation",
    title: "Slash and Punctuation",
    description: "Introduce punctuation keys without losing your relaxed hand shape.",
    focusKeys: [";", ",", ".", "/"],
    text: "ask, add, fall. dad, sad, all. flask / salad / lad.",
  },
  {
    id: "punctuation-rhythm",
    title: "Punctuation Rhythm",
    description: "Keep punctuation light and deliberate so it feels like part of the sentence.",
    focusKeys: [";", ",", ".", "/"],
    text: "we pause, we move, we flow. safe words, calm words / clear words.",
  },
  {
    id: "short-word-control",
    title: "Short Word Control",
    description: "Use small, fast words to sharpen timing without speeding past accuracy.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "e", "r", "i", "o"],
    text: "we do so if all are safe and we feel calm in our flow",
  },
  {
    id: "common-word-builder",
    title: "Common Word Builder",
    description: "Practice everyday words that repeat familiar finger paths.",
    focusKeys: ["q", "w", "e", "r", "u", "i", "o", "p", "a", "s", "d", "f", "j", "k", "l", ";"],
    text: "people use real words and we read quick ideas with clear focus",
  },
  {
    id: "sentence-starter",
    title: "Sentence Starter",
    description: "Shift from word drills into simple sentence rhythm with spaces and punctuation.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "we type with care, and we move with calm focus.",
  },
  {
    id: "sentence-flow",
    title: "Sentence Flow",
    description: "Keep each word connected and let the spaces carry your rhythm forward.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "our hands stay relaxed, our eyes stay ahead, and our timing improves.",
  },
  {
    id: "precision-passages",
    title: "Precision Passages",
    description: "Type longer passages while keeping every reach smooth and intentional.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "we practice each line with patience, steady hands, and clear spacing.",
  },
  {
    id: "rhythm-and-return",
    title: "Rhythm and Return",
    description: "Learn to return to home row naturally after every stretch.",
    focusKeys: ["q", "w", "e", "r", "u", "i", "o", "p", "a", "s", "d", "f", "j", "k", "l", ";", "z", "x", "c", "v", "b", "n", "m"],
    text: "quick moves return home, smooth hands stay loose, and focus stays steady.",
  },
  {
    id: "accuracy-under-length",
    title: "Accuracy Under Length",
    description: "Use longer lines to train consistency instead of rushing for speed.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "as the lesson grows longer, keep your breathing easy and your fingers organized.",
  },
  {
    id: "balanced-sentences",
    title: "Balanced Sentences",
    description: "Handle letters, spaces, and punctuation together in a steady sentence pattern.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "we write clear lines, we pause with care, and we keep our hands in place.",
  },
  {
    id: "speed-with-control",
    title: "Speed With Control",
    description: "Let your tempo rise a little while accuracy stays the priority.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "faster typing still needs control, calm posture, and a light return to home row.",
  },
  {
    id: "advanced-word-combos",
    title: "Advanced Word Combos",
    description: "Use richer word combinations that force more varied finger travel.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "brave minds move quicker when careful practice creates smooth coordination.",
  },
  {
    id: "full-keyboard-review",
    title: "Full Keyboard Review",
    description: "Review the entire beginner board with a calm, complete practice run.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "we use every row with steady focus, careful spacing, and cleaner movement each round.",
  },
  {
    id: "beginner-finale",
    title: "Beginner Finale",
    description: "Finish the course with a full, natural passage that uses the skills you built lesson by lesson.",
    focusKeys: ["a", "s", "d", "f", "j", "k", "l", ";", "q", "w", "e", "r", "u", "i", "o", "p", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/"],
    text: "quick hands and calm focus will carry your typing forward, one clean lesson at a time.",
  },
];

export function getLessonWordCount(lesson) {
  return String(lesson?.text || "")
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
}
